### ISSUE TITLE
[FEATURE] Create favicon

### ISSUE THREAD

**Issue by DandyLyons** [DandyLyons/React-Example#1]
## Requirements
- When viewing the React Example app in my browser, I should be able to see the custom favicon image that you added in browser tab title.

**Comment by DandyLyons** [comment]
The React app needs a favicon. 

https://www.geeksforgeeks.org/how-to-change-the-favicon-in-react-js/

**Comment by Amandaan** [comment]
Hi, I'd like to work on this issue, thanks!

**Comment by DandyLyons** [comment]
Hi Pai, thank you for showing interest. I'd like to get you paired with another classmate so that you/I/we all can get practice pair programming. Dan and Destiny both shared interest in working on an Issue (but they haven't yet commented on an Issue on GitHub). I'd like to pair you with one of them. 

If they don't communicate by Wed. then I'll go ahead and assign this to you. (Another option is you can pair with me.)

(btw, both people in a pair will be given credit for the contribution.)

**Comment by DandyLyons** [comment]
Hi @Amandaan , Dan messaged me on Slack that she'd like to work on this Issue with you. After Dan comments here on this thread, I'll assign her to this Issue as well (so then you'll both be assigned to it). 

Both of you, please download the official Live Share VS Code Extension. Hopefully this should help make pair programming much easier. 

Here's detailed instructions about how to use it. https://code.visualstudio.com/learn/collaboration/live-share

**Comment by DanWang625** [comment]
Hi Daniel, I'd like to work on this issue with Pai, thank you.

**Comment by DandyLyons** [comment]
I'm excited to see the work you two do! Please let me know if you get stuck anywhere. I would love to help out however I can.

**Comment by DanWang625** [comment]
Thank you so much, we'll try our very best

**Comment by DandyLyons** [comment]
I'm reposting what @Amandaan sent me on Slack so that we can all be looped in on the conversation here. Here's her message.

![Screenshot 2023-11-03 at 11 47 13 AM](https://github.com/DandyLyons/React-Example/assets/72824209/b73f0cb0-8e6a-4ad5-97df-70143c354c00)

Great job you two! 🚀 It looks like you successfully pushed your change to your repository. The next step is to make what's called a Pull Request. (A Pull Request in GitHub, is analogous to what GitLab calls a merge request). A Pull Request is a vital skill that will be used on virtually any collaborative project, so it's fantastic that we're getting practice on one right now. 

Here's a tutorial on Pull Request's: https://www.youtube.com/watch?v=8lGpZkjnkt4&pp=ygUMcHVsbCByZXF1ZXN0
And here's a tutorial on writing a quality PR: https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/

It looks like the next step is for you to click the `Compare & Pull Request` button on GitHub. The step after that is very crucial. You want to make sure that you are clearly and concisely communicating the changes you made in your PR and why you made them. This will make it easier for me to review your changes. 

When I review the PR, I might ask for some changes. If so, this is completely normal, and is a part of the process. After I approve of the changes, then I'll merge the PR and it'll be a success. 🎉

P.S. Sorry, I did an example of not-so-great communication! 😅 When I opened this GitHub Issue, I didn't actually include the requirements in the Issue. I've added them now. Please have a look at them at the top of this Issue thread. (They're short.)

**Comment by DandyLyons** [comment]
https://github.com/DandyLyons/React-Example/pull/14

**Comment by DandyLyons** [comment]
Great job! Go to the PR to see my comments.
